### PR TITLE
Pull fresh inventory and data; switch to three-part targets; add observation summary

### LINKED ISSUE #14: Change to 3 target system for long-running targets
This essentially applies to all of the targets in this pipeline, but we should pull the `s3_put` outside of the initial build fxn so that if the `s3_put` fails (for instance, when disconnected from VPN) the whole build doesn't need to happen again. Please see the section that starts with `3 target method` in the Guidelines page here: https://usgs-r.github.io/scipiper/shared_cache.html.

### PR DESCRIPTION
**Pull request by wdwatkins**
Fixes #14 and #15 .  See associated PR in `delaware-model-prep` repo.

I create a new issue #16  to speed to file I/O since there is a lot of that here.  It could potentially be addressed by migrating this to targets.

### CODE REVIEW

File: 30_data_summarize/src/site_summary.R [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    summarize(n_days = n(),
+              median_flow = median(flow_cfs))
+  stopifnot(length(unique(daily_summary$site_id)) == nrow(daily_summary))
+  
+  daily_summary_dv_site_info <- daily_summary %>% 
+    filter(source == 'nwis_dv') %>% 
+    left_join(dv_inventory, by = c(site_id = 'site_no'))
+  
+  daily_summary_uv_site_info <- daily_summary %>% 
+    filter(source == 'nwis_vv') %>%
```
Comment (limnoliver) [inline 30_data_summarize/src/site_summary.R:25]: Is this supposed to say 'uv'?

File: 10_nwis_pull.yml [hunk 2]
```diff
@@ -110,14 +115,18 @@ targets:
...
     command: create_nwis_pull_makefile(makefile=target_name, task_plan=nwis_uv_pull_plan,
-      final_targets = I('10_nwis_pull/out/nwis_uv_data.rds.ind'))
+      final_targets = I('10_nwis_pull/tmp/nwis_uv_data.rds.ind'))
 
-  10_nwis_pull/out/nwis_uv_data.rds.ind:
+  10_nwis_pull/tmp/nwis_uv_data.rds.ind:
     command: loop_tasks(task_plan=nwis_uv_pull_plan, task_makefile='10_nwis_uv_pull_tasks.yml',
       num_tries=I(30), sleep_on_error=I(20))
     depends:
       - 10_nwis_pull/src/nwis_pull.R
```
Comment (lindsayplatt) [inline 10_nwis_pull.yml:124]: This pattern is a bit outdated. We have started combining the "create plan" + "create makefile" + "loop through tasks" steps into a single function/target, often named `do_[something]_tasks`. It just streamlines the main makefiles and also cleans up the task makefiles that aren't checked in to GitHub anyways. 

[Here is an example of a function](https://github.com/USGS-VIZLAB/gw-conditions/blob/main/1_fetch/src/do_gw_fetch.R) that plans, creates, and executes a task makefile. And [here is the corresponding target](https://github.com/USGS-VIZLAB/gw-conditions/blob/main/1_fetch.yml#L39-L46) in the main makefile.

This is just as an FYI. I don't think it isn't necessary to implement since this is already building.

File: 10_nwis_pull/src/nwis_combine_functions.R [hunk 3]
```diff
@@ -4,22 +4,22 @@ combine_nwis_data <- function(ind_file, ...){
...
     flow_dat <- readRDS(rds_files[i]) 
     
     reduced_dat <- convert_to_long(flow_dat)
     
     df_list[[i]] <- reduced_dat
   }
   
-  nwis_df <- do.call("bind_rows", df_list)
-  
+  nwis_df <- data.table::rbindlist(df_list)
```
Comment (lindsayplatt) [inline 10_nwis_pull/src/nwis_combine_functions.R:17]: You don't actually need do.call with `bind_rows`. You can just write as `bind_rows(df_list)`. Which is something I only recently cemented into my brain (clearly wasn't there when we wrote this last summer). 

Is `rbindlist(df_list)` faster than `bind_rows(df_list)`?

File: 30_data_summarize/src/site_summary.R [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+
+summarize_site_observations <- function(target_ind, daily_flow_ind, 
+                                        dv_inventory, uv_inventory) {
+  
+  daily_flow <- readRDS(sc_retrieve(daily_flow_ind, remake_file = '20_data_munge.yml')) 
+  #daily_flow <- readRDS('20_data_munge/out/daily_flow.rds')
+  #dv_inventory <- readRDS('10_nwis_pull/inout/nwis_dv_inventory.rds')
+  #uv_inventory <- readRDS('10_nwis_pull/inout/nwis_uv_inventory.rds')
+  #dv_inventory <- readRDS(sc_retrieve(dv_inventory_ind, remake_file = '20_data_munge.yml'))
+  #uv_inventory <- readRDS(sc_retrieve(uv_inventory_ind, remake_file = '20_data_munge.yml'))
```
Comment (lindsayplatt) [inline 30_data_summarize/src/site_summary.R:11]: This seems like content from when you were testing this that you should delete?

File: 30_data_summarize/src/site_summary.R [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+  
+  
+  daily_summary <- daily_flow %>% 
+    group_by(site_id, source) %>% 
+    summarize(n_days = n(),
+              median_flow = median(flow_cfs))
+  stopifnot(length(unique(daily_summary$site_id)) == nrow(daily_summary))
```
Comment (lindsayplatt) [inline 30_data_summarize/src/site_summary.R:18]: This assumes there is only one "source" per site. Just want to check - that is what we want, correct?

**Review by lindsayplatt — APPROVED** [review]
Didn't find anything that I thought were errors. Just a few questions and one idea about a scipiper "best practice" that may not be worth addressing considering where we are in pipeline tool evolution.

File: 10_nwis_pull/src/nwis_combine_functions.R (hunk 3 above)
Comment (wdwatkins) [reply 10_nwis_pull/src/nwis_combine_functions.R:17]: Yeah, it is quite a bit faster in general.   I didn't compare specifically here though.

File: 30_data_summarize/src/site_summary.R (hunk 5 above)
Comment (wdwatkins) [reply 30_data_summarize/src/site_summary.R:13]: I think so, `daily_flow` is the aggregated uv + dv file, so I'm assuming redundant sources have already been dealt with.

File: 10_nwis_pull/src/nwis_combine_functions.R (hunk 3 above)
Comment (lindsayplatt) [reply 10_nwis_pull/src/nwis_combine_functions.R:17]: I will need to keep `rbindlist` in mind for the future :)

File: 30_data_summarize/src/site_summary.R (hunk 4 above)
Comment (wdwatkins) [reply 30_data_summarize/src/site_summary.R]: done

File: 30_data_summarize/src/site_summary.R (hunk 5 above)
Comment (lindsayplatt) [reply 30_data_summarize/src/site_summary.R:13]: That sounds right. If not, then we have a site that has data from both uv and dv which is not how this is supposed to work, so would be good to stop the code and troubleshoot.

**Comment by lindsayplatt** [comment]
@wdwatkins I just saw that you added docker stuff. Do you want to put brief instructions about running this pipeline via docker in the README?

**Comment by wdwatkins** [comment]
Thanks, forgot the slurm scripts for that too.  Readme is updated.

**Review by lindsayplatt — APPROVED** [review]
Second approval after all the changes were made!
